import { Injectable } from "angular/core"
import { HttpClient } from "@angular/common/http"
import { House } from "./house"
import { Record } from "./record"
import { Room } from "./room"
import { Sensor } from "./sensor"